name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.14.1"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: node.js ${{ matrix.node }} test in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: |
          node -v
          npm -v
          yarn --version

      - name: Install
        run: |
          yarn

      - name: Lint
        run: |
          npm run lint

      - name: Compile
        run: |
          yarn run compile

      - name: Package
        run: |
          npm run pack
